package org.javapro.jtabletoexcel;

import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableModel;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;

public class Demo extends javax.swing.JFrame {

    /**
     * Creates new form Demo
     */
    public Demo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Export");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Workbook workbook = new HSSFWorkbook();
        fillExcelReportContent(workbook);
        exportReport(workbook);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void exportReport(Workbook workbook) throws HeadlessException {
        OutputStream fileOut;
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.addChoosableFileFilter(new FileNameExtensionFilter("Excel file", "xls"));
            int selection = chooser.showSaveDialog(this);
            if (selection == JFileChooser.APPROVE_OPTION) {
                fileOut = enforceExtension(chooser.getSelectedFile());
                workbook.write(fileOut);
                System.out.println("Excel File has been created successfully.");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private OutputStream enforceExtension(File selectedFile) throws FileNotFoundException {
        String fileName = selectedFile.getAbsolutePath();
        File theFile;
        if (!fileName.endsWith(".xls")) {
            theFile = new File(fileName + ".xls");
        } else {
            theFile = selectedFile;
        }
        return new FileOutputStream(theFile);
    }

    private void fillExcelReportContent(Workbook workbook) {
        TableModel internalModel = jTable1.getModel();
        int rows = internalModel.getRowCount();
        int cols = internalModel.getColumnCount();
        //invoking creatSheet() method and passing the name of the sheet to be created
        Sheet sheet = workbook.createSheet("WorkSheet1");
        createHeaderRow(sheet, cols, internalModel);
        createContent(rows, sheet, cols, internalModel);
    }

    private void createContent(int rows, Sheet sheet, int cols, TableModel internalModel) {
        //content
        for (int i = 0; i < rows; i++) {
            Row nthrow = sheet.createRow(i + 1);
            for (int j = 0; j < cols; j++) {
                System.out.println("(" + i + "," + j + ")");
                Object cellValue = internalModel.getValueAt(i, j);
                Cell cell = nthrow.createCell(j);
                String cellValue1 = cellValue.toString();
                System.out.println("cell(" + i + "," + j + ") = {" + cellValue1 + "}");

                cell.setCellValue(cellValue1);
            }
        }
    }

    private void createHeaderRow(Sheet sheet, int cols, TableModel internalModel) {
        //headers
        Row rowhead = sheet.createRow(0);
        for (int i = 0; i < cols; i++) {
            String columnName = internalModel.getColumnName(i);
            rowhead.createCell(i).setCellValue(columnName);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Demo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
